/**
 * Obfuscord — LLMs auto-generator
 *
 * Generates two files from the existing docs + README:
 *   llms.txt       — Compact overview (header template + docs index)
 *   llms-full.txt  — Complete documentation (README + all docs/*.md)
 *
 * Usage:  bun run generate:llms
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join } from 'path'

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __dirname = import.meta.dir
const ROOT = join(__dirname, '..')
const DOCS = join(ROOT, 'docs')
const README = join(ROOT, 'README.md')
const HEADER_TEMPLATE = join(__dirname, 'llms-header.md')
const OUTPUT_LLMS = join(ROOT, 'llms.txt')
const OUTPUT_FULL = join(ROOT, 'llms-full.txt')

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DocEntry {
  /** Relative path from ROOT, e.g. "docs/architecture.md" */
  path: string
  /** First # heading of the document */
  title: string
  /** First paragraph after the heading (~120 chars) */
  description: string
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Extracts the first H1 (# Title) from markdown content. */
function getTitle(content: string): string {
  const match = content.match(/^#\s+(.+)/m)
  return match?.[1] ?? 'Unknown'
}

/** Extracts the first descriptive paragraph after the H1 heading. */
function getDescription(content: string): string {
  const lines = content.split('\n')
  let foundHeading = false

  for (const line of lines) {
    if (!foundHeading && line.startsWith('# ')) {
      foundHeading = true
      continue
    }

    if (
      foundHeading &&
      line.trim() &&
      !line.startsWith('#') &&
      !line.startsWith('---') &&
      !line.startsWith('- [') &&          // Skip TOC links
      !line.startsWith('-')               // Skip list items (TOC)
    ) {
      const trimmed = line.trim()
      return trimmed.length > 120
        ? trimmed.slice(0, 120) + '...'
        : trimmed
    }
  }

  return '-'
}

/** Recursively walks the docs/ directory and collects all .md files. */
function walkDir(dir: string, entries: DocEntry[]): void {
  const items = readdirSync(dir)

  for (const item of items) {
    const full = join(dir, item)
    const stat = statSync(full)

    if (stat.isDirectory()) {
      walkDir(full, entries)
    } else if (item.endsWith('.md')) {
      // Compute relative path from ROOT, e.g. "docs/architecture.md" or "docs/components/ca.md"
      const fullPath = join(dir, item)
      const relative = join('docs', fullPath.startsWith(DOCS)
        ? fullPath.slice(DOCS.length + 1)
        : fullPath
      ).replace(/\\/g, '/')

      const content = readFileSync(full, 'utf-8')
      entries.push({
        path: relative,
        title: getTitle(content),
        description: getDescription(content),
      })
    }
  }
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

/**
 * Builds llms.txt — compact overview with header + docs index.
 */
function generateLlmsTxt(entries: DocEntry[]): string {
  const header = readFileSync(HEADER_TEMPLATE, 'utf-8')

  const lines: string[] = []
  lines.push('')
  lines.push('## Documentation Index')
  lines.push('')
  lines.push('| Document | Description |')
  lines.push('|----------|-------------|')

  for (const entry of entries) {
    // Escape pipe characters in description to keep table valid
    const desc = entry.description.replace(/\|/g, '\\|')
    lines.push(`| [${entry.path}](${entry.path}) | ${desc} |`)
  }

  lines.push('')
  lines.push('---')
  lines.push(
    '*Auto-generated by `scripts/generate-llms.ts`. For full content see [llms-full.txt](llms-full.txt).*',
  )

  return header + '\n' + lines.join('\n')
}

/**
 * Builds llms-full.txt — concatenation of README.md + all docs/*.md.
 */
function generateLlmsFull(entries: DocEntry[]): string {
  const timestamp = new Date().toISOString()

  const parts: string[] = [
    `# Obfuscord — Full Documentation`,
    ``,
    `> Auto-generated from README.md + docs/ — DO NOT EDIT MANUALLY`,
    `> Generated: ${timestamp}`,
    ``,
  ]

  // ----- README.md first -----
  const readmeContent = readFileSync(README, 'utf-8')
  parts.push(`---`)
  parts.push(`<!-- START: README.md -->`)
  parts.push(`---`)
  parts.push('')
  parts.push(readmeContent)
  parts.push('')

  // ----- Each doc file -----
  for (const entry of entries) {
    const fullPath = join(ROOT, entry.path)
    const content = readFileSync(fullPath, 'utf-8')

    parts.push(`---`)
    parts.push(`<!-- START: ${entry.path} -->`)
    parts.push(`---`)
    parts.push('')
    parts.push(content)
    parts.push('')
  }

  // ----- Footer -----
  parts.push(`---`)
  parts.push(
    `*Auto-generated by \`scripts/generate-llms.ts\` on ${timestamp}.*`,
  )
  parts.push(`*Source files: README.md, docs/**/*.md*`)
  parts.push('')

  return parts.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  // 1. Collect all .md files from docs/ recursively
  const entries: DocEntry[] = []
  walkDir(DOCS, entries)

  // 2. Sort: root docs first (architecture, boot-sequence, ...), then components/
  entries.sort((a, b) => {
    const aIsComponent = a.path.startsWith('docs/components/')
    const bIsComponent = b.path.startsWith('docs/components/')
    if (aIsComponent !== bIsComponent) return aIsComponent ? 1 : -1
    return a.path.localeCompare(b.path)
  })

  // 3. Generate
  const llms = generateLlmsTxt(entries)
  const full = generateLlmsFull(entries)

  writeFileSync(OUTPUT_LLMS, llms, 'utf-8')
  writeFileSync(OUTPUT_FULL, full, 'utf-8')

  console.log(`✅ Generated successfully:`)
  console.log(`   ${OUTPUT_LLMS}  (${(llms.length / 1024).toFixed(1)} KB)`)
  console.log(`   ${OUTPUT_FULL} (${(full.length / 1024).toFixed(1)} KB)`)
}

main()
